/* Autogenerated by hxtools bin2c */
#ifdef __cplusplus
extern "C" {
#endif

/* Autogenerated from gitinfo.txt */
static const unsigned char bin2c_gitinfo_txt[42] = "9a05f92 - louis, 3 hours ago : temp_bias\012";

#ifdef __cplusplus
} /* extern "C" */
#endif
