/* Autogenerated by hxtools bin2c */
#ifdef __cplusplus
extern "C" {
#endif

/* Autogenerated from gitinfo.txt */
static const unsigned char bin2c_gitinfo_txt[46] = "1d6db85 - jitdeep chehara, 4 months ago : v4\012";

#ifdef __cplusplus
} /* extern "C" */
#endif
