/* Autogenerated by hxtools bin2c */
#ifdef __cplusplus
extern "C" {
#endif

/* Autogenerated from gitinfo.txt */
static const unsigned char bin2c_gitinfo_txt[20] = "44ab88e-2026-05-27\012";

#ifdef __cplusplus
} /* extern "C" */
#endif
