/* Autogenerated by hxtools bin2c */
#ifdef __cplusplus
extern "C" {
#endif

/* Autogenerated from code_boot.js */
static const unsigned char bin2c_code_boot_js[281] = "\12\12\12function load_code() {\12    var script = document.createElement('script');\12    script.onload = function () {\12        console.log('loading js');\12    };\12    script.src = 'code.js';\12    document.head.appendChild(script); //or something of the likes\12}\12\12setTimeout(load_code, 2000);\012";

#ifdef __cplusplus
} /* extern "C" */
#endif
