/* Autogenerated by hxtools bin2c */
#ifdef __cplusplus
extern "C" {
#endif

/* Autogenerated from page.html */
static const unsigned char bin2c_page_html[1216] = "<!DOCTYPE html>\12<html>\12  <head>\12    <meta http-equiv=\"Content-type\" content=\"text/html; charset=utf-8\" />\12    <meta http-equiv=\"Cache-Control\" content=\"no-cache, no-store, must-revalidate\" />\12    <meta http-equiv=\"Pragma\" content=\"no-cache\" />\12    <meta http-equiv=\"Expires\" content=\"0\" />\12\12    <!-- <link rel='icon' href='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAS0lEQVR42s2SMQ4AIAjE+P+ncSYdasgNXMJgcyIIlVKPIKdvioAXyWBeJmVpqRZKWtj9QWAKZyWll50b8IcL9JUeQF50n28ckyb0ADG8RLwp05YBAAAAAElFTkSuQmCC' type='image/x-png' /> -->\12    <title>Ouverture du garage</title>\12    <style>\12      .bb {\12          font-size: 20px;\12      }\12      .ekocontainer {\12          overflow: \"auto\";\12          overflow-y : \"auto\" ;\12          max-height : \"300px\"          \12      }\12    </style>\12  </head>\12  <body class=\"bb\">\12    <div id=\"statut\"> La porte est ?\077? </div>\12    <div id=\"buttons\" >  </div>\12    <div>\12      <button class=\"bb\", id=\"ouvrir\">Ouvrir</button>\12      <button class=\"bb\", id=\"swap\">Swap</button>    \12    </div>\12    <div id=\"eko\" class=\"ekocontainer\" >  </div>\12    <script type=\"text/javascript\" src=\"code.js?v=RANDOM\" charset=\"utf-8\"></script>        \12  </body>\12  Compilation date : DATE  \12</html>\012";

#ifdef __cplusplus
} /* extern "C" */
#endif
