#line 1 "/mnt/hd3/users/Louis/dev/git/EPortier/ESP8266/iono/gitinfo.h"
/* Autogenerated by hxtools bin2c */
#ifdef __cplusplus
extern "C" {
#endif

/* Autogenerated from gitinfo.txt */
static const unsigned char bin2c_gitinfo_txt[48] = "8370794 - jitdeep chehara, 5 weeks ago : tenda\012";

#ifdef __cplusplus
} /* extern "C" */
#endif
